# Overrides:
#   CLOVER2_DOCKER_IMAGE_TARS: space-separated URLs of docker-save tars
#                               (clover2-docs.tar, clover2-frontend.tar from
#                               the clover2 CI); empty by default
#   CLOVER2_COMPOSE_PROFILES: compose profiles for the drone (default: web)
#   CLOVER2_FRONTEND_PORT: frontend host port (default: 80)

enable_extension "docker-ce"

function extension_prepare_config__clover2_docker() {
	display_alert "clover2-docker: docker-ce + compose v2 will be installed" "${EXTENSION}" "info"
}

function post_family_tweaks__50_clover2_docker() {
	clover2_docker_main
}

clover2_docker_log() {
	display_alert "clover2-docker: $*" "${EXTENSION}" "info"
}

clover2_docker_setup_user() {
	chroot_sdcard "usermod -aG docker ${CLOVER2_USER:-pi}"
}

clover2_docker_install_compose_file() {
	local compose_src="${SDCARD}/opt/clover2/ws/src/clover2/docker/compose.yaml"
	[[ -f "${compose_src}" ]] || exit_with_error "docker/compose.yaml not found - run after the clover2 extension"

	local hash
	hash="$(grep -oP 'CLOVER2_GIT_HASH=\K.*' "${SDCARD}/usr/lib/os-release" 2>/dev/null || true)"
	[[ -n "${hash}" && "${hash}" != "unknown" ]] || hash="latest"

	clover2_docker_log "installing docker-compose.yaml + .env (TAG=${hash}, profiles=${CLOVER2_COMPOSE_PROFILES:-robot})"
	run_host_command_logged cp "${compose_src}" "${SDCARD}/opt/clover2/docker-compose.yaml"

	local env_file="${SDCARD}/opt/clover2/.env"
	cat > "${env_file}" <<EOF
# generated by the clover2-docker armbian extension
TAG=${hash}
COMPOSE_PROFILES=${CLOVER2_COMPOSE_PROFILES:-robot}
FRONTEND_PORT=${CLOVER2_FRONTEND_PORT:-80}
EOF
}

clover2_docker_install_images() {
	local -a tars=()
	read -r -a tars <<< "${CLOVER2_DOCKER_IMAGE_TARS:-}"
	if [[ ${#tars[@]} -eq 0 ]]; then
		display_alert "clover2-docker: CLOVER2_DOCKER_IMAGE_TARS is empty, no images preloaded" \
			"${EXTENSION}" "wrn"
		return 0
	fi

	mkdir -p "${SRC}/cache/clover2/docker"
	local url tar cached
	for url in "${tars[@]}"; do
		tar="$(basename "${url}")"
		cached="${SRC}/cache/clover2/docker/${tar}"
		if [[ ! -f "${cached}" ]]; then
			clover2_docker_log "downloading ${tar}"
			run_host_command_logged curl -fL --retry 3 -o "${cached}" "${url}"
		fi
		run_host_command_logged cp "${cached}" "${SDCARD}/root/${tar}"
	done
}

clover2_docker_main() {
	clover2_docker_setup_user
	clover2_docker_install_compose_file
	clover2_docker_install_images
	clover2_docker_log "done"
}
