BRANCH=current
RELEASE=noble
KERNEL_CONFIGURE=no

KERNELBRANCH="tag:v6.18.52"

BUILD_DESKTOP=yes
DESKTOP_ENVIRONMENT="xfce"
DESKTOP_TIER="minimal"

INCLUDE_HOME_DIR=yes
INSTALL_ARMBIAN_FIRMWARE=no
BUILD_MINIMAL=no
SHARE_LOGS=no

CLOVER2_DEV_COMMIT="vm"

BOARD_NAME="Clover2 VM"
BOARD_MAINTAINER="matveylapin"

VENDOR="Clover2"
MAINTAINER="matveylapin"

FIRST_BOOT_LOAD_CMDLEVEL=1
