BRANCH=current
RELEASE=noble
KERNEL_CONFIGURE=no

BUILD_DESKTOP=yes
DESKTOP_ENVIRONMENT="xfce"
DESKTOP_TIER="minimal"

INCLUDE_HOME_DIR=yes
INSTALL_ARMBIAN_FIRMWARE=no
BUILD_MINIMAL=no
SHARE_LOGS=no

BOARD_NAME="Clover2 VM"
BOARD_MAINTAINER="matveylapin"

VENDOR="Clover2"
MAINTAINER="matveylapin"

FIRST_BOOT_LOAD_CMDLEVEL=1

ENABLE_EXTENSIONS="clover2-vm"

CLOVER2_DEV_COMMIT="vm"
