BRANCH=current
RELEASE=noble
KERNEL_CONFIGURE=no

BUILD_DESKTOP=yes
DESKTOP_ENVIRONMENT="xfce"
DESKTOP_TIER="minimal"

INCLUDE_HOME_DIR=yes
INSTALL_ARMBIAN_FIRMWARE=no
PACKAGE_LIST_RM=armbian-zsh
BUILD_MINIMAL=no
SHARE_LOGS=no

BOARD_NAME="Clover2 VM"
BOARD_MAINTAINER="bart02"

VENDOR="Klever-COEX"
MAINTAINER="bart02"

FIRST_BOOT_LOAD_CMDLEVEL=1

ENABLE_EXTENSIONS="clover2-vm"

CLOVER2_DEV_COMMIT="vm"
