BOARD=rpi4b
BRANCH=current
RELEASE=noble
KERNEL_CONFIGURE=no
BUILD_DESKTOP=no
BUILD_MINIMAL=no
SHARE_LOGS=no
ENABLE_EXTENSIONS="klever5 clover2-image-shrink clover2-image-zip"
INCLUDE_HOME_DIR="yes"

BOARD_NAME="Clover2 RPi 4B"
BOARD_MAINTAINER="matveylapin"
BOARDFAMILY="bcm2711"

VENDOR="Clover2"
MAINTAINER="matveylapin"

FIRST_BOOT_LOAD_CMDLEVEL=1
