BOARD=rpi5b
BRANCH="legacy"
RELEASE=noble

INSTALL_HEADERS=yes
KERNEL_CONFIGURE=no
KERNEL_GIT=shallow

BUILD_DESKTOP=no
BUILD_MINIMAL=no
SHARE_LOGS=no
BOOT_LOGO=no
SKIP_BOOTSPLASH=yes

KERNELBRANCH="commit:2212a454d11b24d171a818fdd709adb4b339ca1f"
PINNED_KERNELBRANCH="commit:2212a454d11b24d171a818fdd709adb4b339ca1f"

INCLUDE_HOME_DIR=yes

BOARD_NAME="Clover2 RPi 5B"
BOARD_MAINTAINER="matveylapin"
BOARDFAMILY="bcm2711"

VENDOR="Klever-COEX"
MAINTAINER="matveylapin"

FIRST_BOOT_LOAD_CMDLEVEL=1

ENABLE_EXTENSIONS="kernel-branch-pin klever5 clover2-image-zip"

# The bcm2711 board unconditionally overrides KERNELBRANCH,
# so use this extension as a workaround
if [[ -n "${PINNED_KERNELBRANCH:-}" ]]; then
	ENABLE_EXTENSIONS="kernel-branch-pin ${ENABLE_EXTENSIONS}"
fi

CLOVER2_COMPOSE_PROFILES="web"
CLOVER2_DDS_DOMAIN_ID=0
CLOVER2_DDS_PROFILE="shm"
CLOVER2_DDS_RMW="fastdds"
CLOVER2_FRONTEND_PORT="80"
CLOVER2_LIBCAMERA_REF="v0.7.1+rpt20260429"
CLOVER2_USER_PASSWORD="raspberry"
CLOVER2_USER="pi"
