BOARD=uefi-x86
BRANCH=current
RELEASE=noble

KERNEL_CONFIGURE=no
KERNEL_GIT=shallow
INSTALL_HEADERS=yes

BUILD_DESKTOP=no
# DESKTOP_ENVIRONMENT="xfce"
# DESKTOP_TIER="minimal"
BUILD_MINIMAL=yes
SHARE_LOGS=no
BOOT_LOGO=no
SKIP_BOOTSPLASH=yes

INCLUDE_HOME_DIR=yes

BOARD_NAME="Clover2 Virtual Box"
BOARD_MAINTAINER="matveylapin"
BOARDFAMILY="uefi-x86"

VENDOR="Clover2"
MAINTAINER="matveylapin"

FIRST_BOOT_LOAD_CMDLEVEL=1
CLOVER2_IMPORT_THIRD_PARTY="no"
ENABLE_EXTENSIONS="clover2-user-setup clover2-ros2 clover2 clover2-image-shrink clover2-image-zip"
