BOARD=rpi5b
BRANCH=current
RELEASE=noble

INSTALL_HEADERS=yes
KERNEL_CONFIGURE=no
KERNEL_GIT=shallow
KERNEL_BTF=no

BUILD_DESKTOP=no
BUILD_MINIMAL=no
SHARE_LOGS=no
BOOT_LOGO=no
SKIP_BOOTSPLASH=yes

INCLUDE_HOME_DIR=yes

BOARD_NAME="Clover2 RPi 5B"
BOARD_MAINTAINER="matveylapin"
BOARDFAMILY="bcm2711"

VENDOR="Clover2"
MAINTAINER="matveylapin"

FIRST_BOOT_LOAD_CMDLEVEL=1

ENABLE_EXTENSIONS="klever5 clover2-image-zip"

CLOVER2_COMPOSE_PROFILES="web"
CLOVER2_DDS_DOMAIN_ID=0
CLOVER2_DDS_PROFILE="shm"
CLOVER2_DDS_RMW="fastdds"
CLOVER2_FRONTEND_PORT="80"
CLOVER2_LIBCAMERA_REF="v0.7.1+rpt20260429"
CLOVER2_USER_PASSWORD="raspberry"
CLOVER2_USER="pi"
