BOARD=uefi-arm64
ENABLE_EXTENSIONS="clover2-vm utm-qcow2"
QCOW2_RESIZE_AMOUNT=+47G

# COMPRESS_OUTPUTIMAGE=sha,xz
# KERNELBRANCH="tag:v6.18.48"

BOARDFAMILY="uefi-arm64"

source "$(dirname "${BASH_SOURCE[0]}")/_config-clover2-vm.conf"
