#!/bin/sh

printf '\n'
. /etc/clover2-release 2>/dev/null
printf 'Project version: \033[0;32m%s\033[0m\n' "${CLOVER2_VERSION:-unknown}"
printf 'Start in browser: \033[0;31mhttp://%s.local\033[0m\n' "$(hostname)"
printf '\n'
