declare -g BOARD_NAME="Klever5 RPi 5B"
declare -g BOARD_VENDOR="Clover2"
declare -g BOARDFAMILY="bcm2711"
declare -g BOARD_MAINTAINER="matveylapin"
declare -g INTRODUCED="2026"
declare -g KERNEL_TARGET="current,edge,legacy"
declare -g ASOUND_STATE="asound.state.rpi"
declare -g MODULES="i2c_dev"
